workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Web Assets
        script: |
          npm run build --if-present
      - name: Add iOS Platform & Sync
        script: |
          node ./node_modules/@capacitor/cli/bin/capacitor add ios
          node ./node_modules/@capacitor/cli/bin/capacitor sync ios
      - name: Build iOS App
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace -scheme App -configuration Release -sdk iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/App/build/**/*.app